version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    versioning-strategy: increase-if-necessary
    rebase-strategy: auto
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major-react-next:
        patterns:
          - "react"
          - "react-dom"
          - "next"
        update-types:
          - "major"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "next"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "UTC"
    commit-message:
      prefix: "ci"
    labels:
      - "ci"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    security-updates-only: true
