version: 2
# Focused on security updates only - Renovate handles regular dependency updates
updates:
  # Security-only updates for npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "UTC"
    # Only security updates to complement Renovate
    security-updates-only: true
    open-pull-requests-limit: 5
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "security"
      - "dependencies"
      - "dependabot"
    allow:
      - dependency-type: "all"
    # Auto-merge security patches
    automerge: true
    
  # GitHub Actions security updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "UTC"
    # Only security updates for GitHub Actions
    security-updates-only: true
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "security"
      - "ci"
      - "dependabot"
    open-pull-requests-limit: 3
